import { describe, expect, it } from 'vitest'
import { SLOW_STAR_SIDES } from './starBattleSlowSides'

/**
 * The measured-slow list is data, not code: it is regenerated by
 * benchmarking the generator per side, and the surface's tests derive their
 * expectations from it. What can be pinned structurally is that it stays a
 * sane list — non-empty, unique, sorted integers — so a careless edit fails
 * here rather than producing a marker no test notices.
 */

describe('SLOW_STAR_SIDES', () => {
  it('is a non-empty list of safe integers', () => {
    expect(SLOW_STAR_SIDES.length).toBeGreaterThan(0)
    for (const side of SLOW_STAR_SIDES) {
      expect(Number.isSafeInteger(side)).toBe(true)
      expect(side).toBeGreaterThan(0)
    }
  })

  it('is sorted ascending with no duplicates', () => {
    const sorted = [...SLOW_STAR_SIDES].sort((a, b) => a - b)
    expect([...SLOW_STAR_SIDES]).toEqual(sorted)
    expect(new Set(SLOW_STAR_SIDES).size).toBe(SLOW_STAR_SIDES.length)
  })

  it('is a readonly array', () => {
    expect(Array.isArray(SLOW_STAR_SIDES)).toBe(true)
  })
})
